### ISSUE TITLE
[ALTA] Maquetado y Estética unificada

### ISSUE THREAD

**Issue by FaustoPigliacampo** [pgPilfs/grupo1a-g1a#18]
Después de la meet del 16-07 se definió la siguiente paleta de colores para utilizar en las distintas secciones de la página:
![Color Hunt Palette](https://user-images.githubusercontent.com/14808591/125965330-768ac9af-0c7d-4d98-9cce-fdc8f5741c5b.png)
(**Codigos en hexadecimal:**
Primero: cdf0ea
Segundo; f9f9f9
Tercero: f7dbf0
Cuarto: beaee2)

Imagen de diseño básico para la pagina principal (El inicio de sesión, la pagina para registrarse y la pagina de bienvenida no llevan la barra lateral de navegación):
![Diseño](https://user-images.githubusercontent.com/14808591/125965801-a5c848cc-29fe-4110-bd2b-ec11ad9b5693.png)

**Comment by FaustoPigliacampo** [comment]
Faltan definir:

Logo de la pagina.
Texto de bienvenida.
Organización Navbar (elementos y prioridad).

**Comment by facuja** [comment]
Página inicial de bienvenida (sin el texto)
![Landing](https://user-images.githubusercontent.com/57334395/125967366-ee80ddb1-76a1-4481-999a-cf035856b9fe.png)

**Comment by FaustoPigliacampo** [comment]
Pagina de bienvenida (Antes de que el usuario ingrese):
